#!/bin/bash
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         RenderLab Theme Verification Tool                    ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 CSS Variables Status:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Active --rl-* tokens: $(grep -c '^  --rl-' app/renderlab-theme.css)"
echo "Active --color-* vars: $(grep -E '^\s+--color-[a-z]' app/globals.css | wc -l | xargs)"
echo "Commented --color-* vars: $(grep -E '^\s+/\* --color-' app/globals.css | wc -l | xargs)"
echo ""
echo "🎨 Theme Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
grep -q 'className="light"' app/layout.tsx && echo "❌ Hardcoded className found" || echo "✅ No hardcoded className"
grep -q 'ThemeProvider' app/layout.tsx && echo "✅ ThemeProvider integrated" || echo "❌ ThemeProvider missing"
grep -q '.dark {' app/renderlab-theme.css && echo "✅ .dark selector configured" || echo "❌ Wrong dark mode selector"
grep -q 'bg-neutral-50' app/layout.tsx && echo "❌ Hardcoded bg-neutral-50" || echo "✅ No hardcoded body background"
echo ""
echo "🏗️  Build Status:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next.js process: $(pgrep -f 'next dev' > /dev/null && echo '✅ Running' || echo '❌ Not running')"
echo ""
echo "📝 Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Open http://localhost:3000/workspace in browser"
echo "2. Hard refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo "3. Open DevTools → Elements → <html> → Check class attribute"
echo "4. Open DevTools → Elements → <html> → Styles → Check :root"
echo "5. Verify panels show semi-transparent white backgrounds"
echo ""
